DROP TABLE IF EXISTS authors;
CREATE TABLE authors
(
    id   BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

DROP TABLE IF EXISTS genres;
CREATE TABLE genres
(
    id    BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255)
);

DROP TABLE IF EXISTS books;
CREATE TABLE books
(
    id             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title          VARCHAR(255),
    author_id      BIGINT,
    genre_id       BIGINT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES authors (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES genres (ID) ON DELETE CASCADE ON UPDATE CASCADE
);
