spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  info:
    git:
      mode: full
  cors:
    allowed-origins: http://localhost:9090/
    allowed-methods: GET,POST,OPTIONS

logging:
  file:
    name: log.txt

info:
  version: @project.version@
  author: Al
  descriptiion: This is Spring Bot example

hystrix:
  dashboard:
    proxy-stream-allow-list:
      - 'localhost'